### ISSUE TITLE
[fr] Correction dans le text blogué au 4/01/200

### ISSUE THREAD

**Issue by XavCC** [Te-k/blog#1]
J'aime bien vous lire alors je rapporte quelques fautes dans votre texte, dans une volonté d'aider et contribuer à améliorer. En espérant ne pas être ennuyeux dans ma démarche, si c'est le cas, fermez cette issue et je comprendrais.

Dans [Cas Pratique d'OSINT : enquêter sur un site web - ivg.net](Te-k/blog/blob/master/fr/post/index.xml),

Voici quelques erreurs repérées :

+ «  fournir plus de contenu`s` accessibles » (manque un `s`)
+ « liens entre~~s~~ des » (un `s` en trop)
+ « rien de semble relié » peut-être « ne semble » ?
+ « mais le fait de les avoir enregistré~~s~~ » (un `s` en trop)
+ « Une vérification~~s~~ » (un `s` en trop)

Au plaisir de continuer à vous lire.

**Comment by Te-k** [comment]
Merci beaucoup !
